apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-release
  labels:
    app: worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: INTERVAL
              value: {{ .Values.env.INTERVAL | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
